spring:
  application:
    name: wp-app
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER_HOST:localhost:19092}
    consumer:
      group-id: person-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://${SCHEMA_REGISTRY_HOST:localhost:8081}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      schema.registry.url: http://${SCHEMA_REGISTRY_HOST:localhost:8081}
    listener:
      idle-event-interval: 30000
      poll-timeout: 2000
    properties:
      # VERY IMPORTANT !!!!!!!!!
      auto.register.schemas: false
      allow.auto.create.topics: false
      specific.avro.reader: true
      avro.remove.java.properties: true
      # not very important
      schema.registry.url: http://${SCHEMA_REGISTRY_HOST:localhost:8081}

person-topic.name: person-topic